### ISSUE TITLE
Runtime migrations tracking issue

### ISSUE THREAD

**Issue by apopiak** [hicommonwealth/edgeware-node#164]
This issue tracks the runtime migrations necessary for the edgeware chain upgrade.
Based on [PRs with migrations hackMD](https://hackmd.io/p97ldDxfST6WF-1m-MxwOA) as well as [Substrate PRs labeled `D1-runtime-migration`](https://github.com/paritytech/substrate/issues?q=label%3AD1-runtime-migration+).

## Migration Strategy
General strategy:
1. pre-hasher migrations first in custom runtime migration [here](https://github.com/hicommonwealth/edgeware-node/blob/time-travel/node/runtime/src/lib.rs#L854)
2. hasher migration including account migration as the last migration in the custom migration
3. post-hasher migrations that assume up-to-date hashers in the modules

Some pallets need to go through this flow in a custom way (e.g. staking combines a pre- and post-hasher migration (lazy and simple payouts)).

## Relevant Migration PRs
Last commit in `v1.0.1redo` was on `2020-02-13`.

These might include more than one logical migration each.
+ [x] `2020-02-01`: balances refactor: https://github.com/paritytech/substrate/pull/4649 
  + addressed: https://github.com/hicommonwealth/substrate/pull/6
+ [x] `2020-02-14`: composite accounts: https://github.com/paritytech/substrate/pull/4820 (includes indices migration removed in https://github.com/paritytech/substrate/pull/5870)
  + addressed: https://github.com/hicommonwealth/substrate/pull/14
+ [x] `2020-02-24`: lazy reaping https://github.com/paritytech/substrate/pull/4895
  + addressed: https://github.com/hicommonwealth/substrate/pull/6/
+ [x] `2020-03-03`: lazy payouts https://github.com/paritytech/substrate/pull/4474
  + addressed: https://github.com/hicommonwealth/edgeware-node/pull/173 and https://github.com/hicommonwealth/substrate/pull/10
+ [x] `2020-03-05`: introduce `on_runtime_upgrade` https://github.com/paritytech/substrate/pull/5058 (includes balances migration, removed in  https://github.com/paritytech/substrate/pull/5224 )
+ [x] `2020-03-14`: unique storage names: https://github.com/paritytech/substrate/pull/5010/ 
  + addressed: https://github.com/hicommonwealth/substrate/pull/6

⬆️ pre-hasher migrations

+ [x] `2020-03-16`: iterable storage maps (away from opaque hashes): https://github.com/paritytech/substrate/pull/5226 
  + addressed: https://github.com/hicommonwealth/substrate/pull/6 https://github.com/hicommonwealth/edgeware-node/pull/170

⬇️ post-hasher migrations

+ [x] `2020-03-21`: democracy redesign: https://github.com/paritytech/substrate/pull/5294/
  + addressed: https://github.com/hicommonwealth/substrate/pull/12
+ [x] `2020-03-23`: prime member selection: https://github.com/paritytech/substrate/pull/5346
  + addressed: https://github.com/hicommonwealth/substrate/pull/11 and https://github.com/hicommonwealth/edgeware-node/pull/174
+ [x] `2020-03-26`: scheduler introduction (and democracy refactoring), no migration in substrate, but requires one for edgeware: https://github.com/paritytech/substrate/pull/5412
  + addressed: https://github.com/hicommonwealth/substrate/pull/12
+ [x] `2020-04-04`: simple staking payouts: https://github.com/paritytech/substrate/pull/5406
  + addressed: https://github.com/hicommonwealth/edgeware-node/pull/173 and https://github.com/hicommonwealth/substrate/pull/10
+ [x] `2020-04-17`: fee multiplier: https://github.com/paritytech/substrate/pull/5673
  + addressed: https://github.com/hicommonwealth/substrate/pull/6
+ [x] `2020-05-15`: democracy weights (flip deposit order of fields): https://github.com/paritytech/substrate/pull/5828
  + addressed: https://github.com/hicommonwealth/substrate/pull/12
+ [x] `2020-06-08`: stacked filtering (multisigs) https://github.com/paritytech/substrate/pull/6273
  + addressed: https://github.com/hicommonwealth/substrate/pull/15
+ [x] `2020-06-09`: frozen indices: https://github.com/paritytech/substrate/pull/6307/
  + addressed: https://github.com/hicommonwealth/substrate/pull/14
+ [x] `2020-06-17`: next fee multiplier: https://github.com/paritytech/substrate/pull/6334/
  + addressed: https://github.com/hicommonwealth/substrate/pull/15

### Removed Migrations
+ [x] `2020-03-12`: https://github.com/paritytech/substrate/pull/5224 (balances)
+ [x] `2020-03-19`: https://github.com/paritytech/substrate/pull/5291 (mostly account/hasher migration, epochs, opaque hashers, grandpa authorities)
+ [x] `2020-05-03`: https://github.com/paritytech/substrate/pull/5870 (Democracy, Indices, Offences, Staking, Transaction Payment)
  + [indices migration here](https://github.com/paritytech/substrate/pull/5870/files#diff-12b2ce0dfddc1915cd81a902d368c2e7L246) is addressed in https://github.com/hicommonwealth/substrate/pull/14
+ [x] `2020-06-24`: https://github.com/paritytech/substrate/pull/6476 (Democracy, Indices, Multisigs, Staking, Transaction Payment)
  + multisig migration removed here is relevant (introduced by https://github.com/paritytech/substrate/pull/6273) and is addressed by https://github.com/hicommonwealth/substrate/pull/15

## Maybe Relevant Migrations
+ ~`2020-03-26`: time module usage in staking https://github.com/paritytech/substrate/pull/4662~
+ ~`2020-04-24`: staking migration code https://github.com/paritytech/substrate/pull/5768~
+ ~`2020-06-05`: staking remove era migration: https://github.com/paritytech/substrate/pull/6253~

### Removed Migrations

**Comment by drewstone** [comment]
Thanks for sharing! Will keep an eye on this here as well. I've also gone ahead with updating the branch with more recent substrate versions (on our fork). I'll link you there so we can make sure we're not stepping on each others feet, though I presume updating the `time-travel` node shouldn't change your efforts.

**Comment by drewstone** [comment]
@apopiak would you be able to document how you're running the upgrades/tests? Are you using Alice/bob accounts. Would be appreciated to keep the info here as up-to-date :)!

**Comment by apopiak** [comment]
Build:
```sh
cargo build --release
```
Purge:
```sh
./target/release/edgeware purge-chain -y --chain=./chains/hybrid-mainnet-dev.json
```
Run:
```sh
#!/usr/bin/env bash
timestamp=$(date +%s)
mkdir -p ./logs
./target/release/edgeware --chain=./chains/hybrid-mainnet-dev.json --alice -lruntime=debug |& tee logs/${timestamp}.log
```

Then I connect with polkadot-js apps to the local node and:
+ run `sudo > setBalance` to increase Alice's balance (with Alice's account, she is configured as sudo).
+ run `sudo > setCodeWithoutChecks` with Alice's account.

**Comment by apopiak** [comment]
Do we need to migrate authorities?
https://github.com/paritytech/substrate/pull/5226/files#diff-74f259f248f6d1f0adbc9b87d8bc322dR212

**Comment by apopiak** [comment]
> Do we need to migrate authorities?
> https://github.com/paritytech/substrate/pull/5226/files#diff-74f259f248f6d1f0adbc9b87d8bc322dR212

Nope, removed the code.

**Comment by apopiak** [comment]
Found a missing migration: [indices migration](https://github.com/paritytech/substrate/pull/5870/files#diff-12b2ce0dfddc1915cd81a902d368c2e7L246).

**Comment by apopiak** [comment]
removed the pallet listing, leaving it here just in case:
#### Pallets
+ System: frame_system
+ Utility: pallet_utility
+ Aura: pallet_aura
+ Timestamp: pallet_timestamp
+ Authorship: pallet_authorship
+ Indices: pallet_indices
+ Balances: pallet_balances
+ TransactionPayment: pallet_transaction_payment
+ Staking: pallet_staking
+ Session: pallet_session
+ Democracy: pallet_democracy
+ Council: pallet_collective::<Instance1>
+ Elections: pallet_elections_phragmen
+ FinalityTracker: pallet_finality_tracker
+ Grandpa: pallet_grandpa
+ Treasury: pallet_treasury
+ Contracts: pallet_contracts
+ Sudo: pallet_sudo
+ ImOnline: pallet_im_online
+ AuthorityDiscovery: pallet_authority_discovery
+ Offences: pallet_offences
+ RandomnessCollectiveFlip: pallet_randomness_collective_flip
+ Identity: pallet_identity
+ Scheduler: pallet_scheduler
+ Vesting: pallet_vesting
+ EVM: pallet_evm
+ Historical: pallet_session_historical
+ Signaling: signaling
+ Voting: voting
+ TreasuryReward: treasury_reward

**Comment by apopiak** [comment]
Migration was run.
