### ISSUE TITLE
Uniswap Edgeware integration issue tracker

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/edgeware-node#201]
- [x] Frontier
- [x] Deploy Uniswap contracts
- [x] Interact with Uniswap contracts
- [x] Deploy some ERC20 tokens
- [ ] Fix "addLiquidity" call on `edgeware-frontier`
- [ ] Launch Uniswap UI https://github.com/Uniswap/uniswap-interface
- [x] Query Uniswap with SDK
- [ ] Document process and add any tooling
